In [3]:
import torch

print(torch.__version__)

2.8.0+cu126


##Introduction to Tensor

###Tensor are the way to represent data (multi-dimensional) numeric way

In [ ]:
## Creating tensor

scalar = torch.tensor(7) ##A torch.Tensor is a multi-dimensional matrix containing elements of a single data type.
scalar

tensor(7)

In [ ]:
#check the dimensions (ndim number of dimensions)
scalar.ndim

0

In [ ]:
#Get tensor back as an python int
scalar.item()

7

In [ ]:
#Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
#MATRIX
MATRIX = torch.tensor([[7,8],[9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX[1]

tensor([ 9, 10])

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
#Tensor
TENSOR = torch.tensor([[[1,2],[3,6],[2,4]]])
TENSOR

tensor([[[1, 2],
         [3, 6],
         [2, 4]]])

In [ ]:
TENSOR.shape

torch.Size([1, 3, 2])

#RANDOM TENSORS

Random tensors are very important becasue the way most of the neural netorks learn is that they start starts with full of random tensors and then adjust it to better represent the data

`Start with random numbers => look at the data => update the random numbers => look at data => update the random numbers`


In [ ]:
RANDOM_TENSORS = torch.rand(4)
RANDOM_TENSORS

tensor([0.4925, 0.7927, 0.5219, 0.6317])

In [ ]:
RANDOM_TENSORS = torch.rand(3,4)
RANDOM_TENSORS

tensor([[0.9840, 0.7028, 0.2537, 0.1702],
        [0.6098, 0.9079, 0.6550, 0.7215],
        [0.9948, 0.2331, 0.0337, 0.6374]])

In [ ]:
#Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224,224,3))   #height,width,number of color channels (R,G,B)
random_image_size_tensor

tensor([[[0.6023, 0.4794, 0.4304],
         [0.2472, 0.3556, 0.5148],
         [0.5863, 0.0559, 0.9286],
         ...,
         [0.9101, 0.8910, 0.0240],
         [0.6824, 0.8387, 0.2491],
         [0.7763, 0.9774, 0.8969]],

        [[0.6405, 0.5613, 0.5875],
         [0.5769, 0.2474, 0.7903],
         [0.2913, 0.3482, 0.8758],
         ...,
         [0.1273, 0.7600, 0.0017],
         [0.0472, 0.9493, 0.4571],
         [0.1142, 0.3723, 0.3875]],

        [[0.5191, 0.6965, 0.8263],
         [0.7970, 0.0814, 0.5826],
         [0.2526, 0.9183, 0.6615],
         ...,
         [0.1091, 0.9361, 0.9021],
         [0.7885, 0.9680, 0.2438],
         [0.3009, 0.4315, 0.1565]],

        ...,

        [[0.0996, 0.4746, 0.5344],
         [0.0409, 0.8842, 0.7860],
         [0.8876, 0.9518, 0.2729],
         ...,
         [0.6511, 0.0609, 0.2393],
         [0.5395, 0.5381, 0.8223],
         [0.6435, 0.7541, 0.5897]],

        [[0.5844, 0.0163, 0.5026],
         [0.1350, 0.8911, 0.1788],
         [0.

###Zeros and Ones Tensor

In [6]:
#Creating a tensor with only zeros
zeros = torch.zeros(4,2,3)
zeros

tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])

In [8]:
#Creating a tensor witl all ones
ones = torch.ones(size=(4,2,3))
ones

tensor([[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]])

In [9]:
ones.dtype

torch.float32

In [10]:
zeros.dtype

torch.float32

###Creating a range of tensors and tensors-like

In [20]:
one_to_ten_four = torch.arange(0,10,4) #first number is the starting point, second number is the ending point, and 3rd number is the number of sequence (in our case multiples of 4)
one_to_ten_four

tensor([0, 4, 8])

In [22]:
#Creating tensors-like
ten_zeros = torch.zeros_like(input=one_to_ten_four)
ten_zeros

tensor([0, 0, 0])

###Tensors Data types

In [3]:
float_32_tensors = torch.tensor([3.0,4.0,5.0],
                                dtype=torch.float32, #Data type
                                device='cpu', #what device it runs on cpu|gpu(cuda)|tpu etc
                                requires_grad=False #whether or not track gradiants with this tensor
                                )
float_32_tensors

tensor([3., 4., 5.])

In [4]:
float_32_tensors.dtype

torch.float32

##Getting information from tensors

###Three big problem with the neural networks
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [11]:
#Creating a tensor
some_tensor = torch.rand(4,4, device='cuda') #cuda for gpu

#Find the details of tensors
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}") #shape or size both same
print(f"Device of tensor: {some_tensor.device}")

tensor([[0.3529, 0.3920, 0.0093, 0.7303],
        [0.2740, 0.6743, 0.4491, 0.0403],
        [0.3154, 0.0848, 0.8246, 0.6166],
        [0.8801, 0.7376, 0.6002, 0.8566]], device='cuda:0')
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([4, 4])
Device of tensor: cuda:0


In [12]:
#checking the time
%%time
some_tensor*some_tensor

CPU times: user 0 ns, sys: 661 µs, total: 661 µs
Wall time: 452 µs


tensor([[1.2454e-01, 1.5367e-01, 8.7087e-05, 5.3330e-01],
        [7.5079e-02, 4.5462e-01, 2.0167e-01, 1.6270e-03],
        [9.9492e-02, 7.1968e-03, 6.8000e-01, 3.8014e-01],
        [7.7454e-01, 5.4408e-01, 3.6023e-01, 7.3374e-01]], device='cuda:0')

In [13]:
%%time
torch.matmul(some_tensor,some_tensor)

CPU times: user 23.5 ms, sys: 6.88 ms, total: 30.4 ms
Wall time: 123 ms


tensor([[0.8776, 0.9421, 0.6253, 0.9048],
        [0.4586, 0.6299, 0.6999, 0.5387],
        [0.9373, 0.7056, 1.0911, 1.2703],
        [1.4559, 1.5251, 1.3485, 1.7762]], device='cuda:0')

###Reshaping, stacking, squeezing, and unsqueezing tensors
* Reshaping - reshape an input tensor to required shape
* View - return a view of an input tensor
* Stacking - combine multiple tensors in a stack (vstack - vertical or hstack - horizontal)
* Squeezing - removes all `1` dimensions from a tensor
* Unsqueezing - add a `1` dimension to a tensor
* Permute - Return a view with dimensions permuted (swaped) in a certain way

In [14]:
#create a tensor
x = torch.arange(0,10,1)
x, x.shape

(tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([10]))

In [23]:
#adding an additional dimension
x_reshape = x.reshape(1,10)
x_reshape, x_reshape.shape

(tensor([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 10]))

In [30]:
#changing the view, z&x here shares the same memory just different way to show the tensor
z = x.view(1,10)
z, z.shape

(tensor([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 10]))

In [31]:
#chane the value to check if they both share the same memory
z[:,1] = 90
z,x

(tensor([[ 0, 90,  2,  3,  4,  5,  6,  7,  8,  9]]),
 tensor([ 0, 90,  2,  3,  4,  5,  6,  7,  8,  9]))

In [37]:
#stack the tensors
stack_tensors = torch.stack([x,x,x,x,x,x,x,x],dim=0)
stack_tensors

tensor([[ 0, 90,  2,  3,  4,  5,  6,  7,  8,  9],
        [ 0, 90,  2,  3,  4,  5,  6,  7,  8,  9],
        [ 0, 90,  2,  3,  4,  5,  6,  7,  8,  9],
        [ 0, 90,  2,  3,  4,  5,  6,  7,  8,  9],
        [ 0, 90,  2,  3,  4,  5,  6,  7,  8,  9],
        [ 0, 90,  2,  3,  4,  5,  6,  7,  8,  9],
        [ 0, 90,  2,  3,  4,  5,  6,  7,  8,  9],
        [ 0, 90,  2,  3,  4,  5,  6,  7,  8,  9]])

In [38]:
stack_tensors.shape

torch.Size([8, 10])

In [47]:
print(f"z = {z}\n z.shape = {z.shape}")
print(f"z.squeeze() = {z.squeeze()}\n z.squeeze().shape = {z.squeeze().shape}")
print(f"z.unsqueeze(dim=0) = {z.unsqueeze(dim=0)}\n z.unsqueeze(dim=0).shape = {z.unsqueeze(dim=0).shape}")

z = tensor([[ 0, 90,  2,  3,  4,  5,  6,  7,  8,  9]])
 z.shape = torch.Size([1, 10])
z.squeeze() = tensor([ 0, 90,  2,  3,  4,  5,  6,  7,  8,  9])
 z.squeeze().shape = torch.Size([10])
z.unsqueeze(dim=0) = tensor([[[ 0, 90,  2,  3,  4,  5,  6,  7,  8,  9]]])
 z.unsqueeze(dim=0).shape = torch.Size([1, 1, 10])


##INDEXING

In [48]:
import torch

In [49]:
x = torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [50]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [51]:
x[0][0]

tensor([1, 2, 3])

In [52]:
x[0][1][0]

tensor(4)

In [53]:
x[0][1][0] = 999
x

tensor([[[  1,   2,   3],
         [999,   5,   6],
         [  7,   8,   9]]])

##REPRODUCIBILITY (trying to take out random out of random)

Every time you use `torch.rand` it will gives you a different random numbers. But what if you want the random numbers to be less random everytime you run your code.

To reduce the randomness in neural networks and PyTorch comes with a concept of a **random seed**

Essiantially what random seed does is flavour the randomness

In [55]:
torch.rand(3,4)

tensor([[0.3431, 0.5269, 0.7820, 0.7685],
        [0.5475, 0.6939, 0.8661, 0.2073],
        [0.6936, 0.5828, 0.7984, 0.5004]])

In [4]:
# lets make some random but reproducible tensors
RANDOM_SEED = 42 #42 is the most common one

torch.manual_seed(RANDOM_SEED)
random_tensor_a = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)
random_tensor_b = torch.rand(3,4)

print(random_tensor_a)
print(random_tensor_b)
print(random_tensor_b == random_tensor_a)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


In [58]:
torch.manual_seed(RANDOM_SEED)
random_tensor_c = torch.rand(3,4)

print(random_tensor_c==random_tensor_a)

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


Check for GPU access with PyTorch

In [1]:
import torch

torch.cuda.is_available()

True

In [2]:
!nvidia-smi

Mon Sep  1 20:33:35 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 581.15                 Driver Version: 581.15         CUDA Version: 13.0     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                  Driver-Model | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce GTX 1650 Ti   WDDM  |   00000000:01:00.0 Off |                  N/A |
| N/A   43C    P3             12W /   30W |       0MiB /   4096MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [5]:
#Device agnostic code

device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [ ]:
#Best Practices for Device agnostic code
import argparse
import torch

parser = argparse.ArgumentParser(description='PyTorch Example')
parser.add_argument('--disable-cuda', action='store_true',
                    help='Disable CUDA')
args = parser.parse_args()
args.device = None
if not args.disable_cuda and torch.cuda.is_available():
    args.device = torch.device('cuda')
else:
    args.device = torch.device('cpu')

usage: ipykernel_launcher.py [-h]
ipykernel_launcher.py: error: unrecognized arguments: --f=c:\Users\umarr\AppData\Roaming\jupyter\runtime\kernel-v3c647eb9b4d8b9961073e83f90ce516e4c8b31257.json


SystemExit: 2

In [ ]:
# Count the number of GPUs

torch.cuda.device_count()

1

Puting tensors and models on the GPU

The reason we want tensors/models on the GPU because using a GPU will result in faster calculations.

In [13]:
#creating a tensor by default using cpu

tensor = torch.tensor([1,2,3])

tensor, tensor.device

(tensor([1, 2, 3]), device(type='cpu'))

In [14]:
#Move tensors to GPU if available

tensor_with_gpu = tensor.to(device)

tensor_with_gpu, tensor_with_gpu.device

(tensor([1, 2, 3], device='cuda:0'), device(type='cuda', index=0))

In [17]:
tensor_with_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [ ]:
#Moving tensor back to CPU (if tensors on GPU, can't transfer it to numpy as numpy only uses CPU)

tensor_with_cpu = tensor_with_gpu.to('cpu')
tensor_with_cpu, tensor_with_cpu.device

(tensor([1, 2, 3]), device(type='cpu'))

In [18]:
tensor_with_cpu.numpy()

array([1, 2, 3])